server:
  port: 8080
  servlet:
    context-path: /mallAdmin

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ivy_mall?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 123456

    mybatis:
      configuration:
        map-underscore-to-camel-case: true


  redis:
    isRedisCache: 1   #是否使用redis缓存
    database: 0       # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址
    port: 6379        # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    timeout: 5000    # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 1000   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
